version: "3.1"

services:
  database:
    image: postgres
    platform: linux/arm64
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
